name: Reusable CI Workflow

on:
  workflow_call:
    outputs:
      buildoutput: 
        description: 'Output from build job'
        value: ${{ jobs.build.outputs.testOutput }}
      

jobs:
  build:
    runs-on: windows-latest
    outputs:
      testOutput: ${{ steps.mapoutput.outputs.buildoutput }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.4.0
        
      # Install dotnet sdk
      - name: Setup dotnet CLI
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
        
      # Map gitversion to an output, note: for running in powershell, use $env:GITHUB_OUTPUT, in bash use $GITHUB_OUTPUT
      - name: Map output value
        id: mapoutput
        run: echo "buildoutput=build_output" >> $env:GITHUB_OUTPUT
      
      # Archive
      - name: Archive
        run: |
          cd ${{ github.workspace }}
          Compress-Archive -Path .\README.md -DestinationPath .\readme.zip
      
      # Publish artifacts to github
      - name: Publish build artifacts
        uses: actions/upload-artifact@v3.1.2
        with: 
          name: drop
          path: ${{ github.workspace }}\readme.zip
          if-no-files-found: error
