name: Reusable CI Workflow

on:
  workflow_call:
    outputs:
      fullSemVersion: 
        description: 'The calculated full semantic version of the build'
        value: ${{ jobs.build.outputs.fullSemVerOutput }}
      

jobs:
  build:
    runs-on: windows-latest
    outputs:
      fullSemVerOutput: ${{ steps.mapgitversion.outputs.fullSemVersion }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.4.0
        
      # Install dotnet sdk
      - name: Setup dotnet CLI
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
        
      # Install gitversion tool
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
          
      # Determine gitversion
      - name: Determine GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true
          configFilePath: GitVersion.yml
        
      # Map gitversion to an output, note: for running in powershell, use $env:GITHUB_OUTPUT, in bash use $GITHUB_OUTPUT
      - name: Map GitVersion
        id: mapgitversion
        run: echo "fullSemVersion=${{ steps.gitversion.outputs.fullSemVer }}" >> $env:GITHUB_OUTPUT
      
      # Archive
      - name: Archive
        run: |
          cd ${{ github.workspace }}
          Compress-Archive -Path .\README.md -DestinationPath .\readme.zip
      
      # Publish artifacts to github
      - name: Publish build artifacts
        uses: actions/upload-artifact@v3.1.2
        with: 
          name: drop
          path: ${{ github.workspace }}\readme.zip
          if-no-files-found: error
